"""add user preferences

Revision ID: 27bb71a41a0b
Revises: 
Create Date: 2026-04-03 23:16:33.109354

"""
from collections.abc import Sequence
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, JSONB
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '27bb71a41a0b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', UUID(as_uuid=True), primary_key=True),
        sa.Column('email', sa.String(), nullable=False, unique=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('profile_picture', sa.String(), nullable=True),
        sa.Column('google_id', sa.String(), nullable=True, unique=True),
        sa.Column('email_notifications', sa.Boolean(), nullable=False, server_default='true'),
    )

    op.create_table(
        'digests',
        sa.Column('id', UUID(as_uuid=True), primary_key=True),
        sa.Column('user_id', UUID(as_uuid=True), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('current_step', sa.String(), nullable=True),
        sa.Column('auto_digest', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('status', sa.String(), nullable=False, server_default='pending'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
        sa.Column('next_delivery', sa.DateTime(), nullable=False, server_default=sa.text("NOW() + INTERVAL '7 days'")),
        sa.Column('delivery_time', sa.String(), nullable=False, server_default='08:00'),
        sa.Column('delivery_day', sa.String(), nullable=False, server_default='Monday'),
        sa.Column('extra_data', JSONB(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('digests')
    op.drop_table('users')
    # ### end Alembic commands ###
