"""add user preferences

Revision ID: 27bb71a41a0b
Revises: 
Create Date: 2026-04-03 23:16:33.109354

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '27bb71a41a0b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('digests', 'next_delivery',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("(now() + '7 days'::interval)"))
    
 
    op.add_column('users', sa.Column('delivery_time', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=True))
    
    
    op.execute("UPDATE users SET delivery_time = '09:00', email_notifications = true")
    
    # Step 3: Make them NOT NULL
    op.alter_column('users', 'delivery_time', nullable=False)
    op.alter_column('users', 'email_notifications', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications')
    op.drop_column('users', 'delivery_time')
    op.alter_column('digests', 'next_delivery',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text("(now() + '7 days'::interval)"))
    # ### end Alembic commands ###
