"""add current_step to digests

Revision ID: 44f2df2f0f71
Revises: 8ca818b18062
Create Date: 2026-04-12 00:22:47.540307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f2df2f0f71'
down_revision: Union[str, Sequence[str], None] = '8ca818b18062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    #op.add_column('digests', sa.Column('current_step', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digests', 'current_step')
    # ### end Alembic commands ###
