"""add cascade delete to digests user_id

Revision ID: 8ca818b18062
Revises: 6b72b018a207
Create Date: 2026-04-10 02:33:23.351477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca818b18062'
down_revision: Union[str, Sequence[str], None] = '6b72b018a207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('digests_user_id_fkey', 'digests', type_='foreignkey')
    op.create_foreign_key(
        'digests_user_id_fkey',
        'digests', 'users',
        ['user_id'], ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('digests_user_id_fkey', 'digests', type_='foreignkey')
    op.create_foreign_key(
        'digests_user_id_fkey',
        'digests', 'users',
        ['user_id'], ['id']
    )
    # ### end Alembic commands ###
