"""add digest cache

Revision ID: 990a57ce477c
Revises: a9fa06e421a3
Create Date: 2026-05-10 18:58:02.258818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '990a57ce477c'
down_revision: Union[str, Sequence[str], None] = 'a9fa06e421a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('digest_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('topic_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('digest_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['digest_id'], ['digests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
        "CREATE INDEX digest_cache_embedding_idx ON digest_cache "
        "USING hnsw (topic_embedding vector_cosine_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('digest_cache')
    # ### end Alembic commands ###
