"""add auto_digest to digests

Revision ID: a9fa06e421a3
Revises: b17a7a103d2d
Create Date: 2026-04-14 20:49:06.853241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9fa06e421a3'
down_revision: Union[str, Sequence[str], None] = 'b17a7a103d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    #op.add_column('digests', sa.Column('auto_digest', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digests', 'auto_digest')
    # ### end Alembic commands ###
