"""add delivery_day to users

Revision ID: b17a7a103d2d
Revises: 44f2df2f0f71
Create Date: 2026-04-14 18:55:39.015014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b17a7a103d2d'
down_revision: Union[str, Sequence[str], None] = '44f2df2f0f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('digests', sa.Column('delivery_day', sa.String(), nullable=False, server_default='Monday'))
    op.add_column('digests', sa.Column('delivery_time', sa.String(), nullable=False, server_default='08:00'))
    
    op.drop_column('users', 'delivery_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('delivery_time', sa.String(), nullable=True)
    )

    op.drop_column('digests', 'delivery_day')
    # ### end Alembic commands ###
