"""decouple_digest_cache

Revision ID: c4ac08272d18
Revises: 1ff39bd73ec2
Create Date: 2026-06-15 10:27:49.905377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4ac08272d18'
down_revision: Union[str, Sequence[str], None] = '1ff39bd73ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digest_cache', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('digest_cache', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('digest_cache_embedding_idx'), table_name='digest_cache', postgresql_ops={'topic_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint(op.f('digest_cache_digest_id_fkey'), 'digest_cache', type_='foreignkey')
    op.drop_column('digest_cache', 'digest_id')
    op.execute(
        "CREATE INDEX digest_cache_embedding_idx ON digest_cache "
        "USING hnsw (topic_embedding vector_cosine_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('digest_cache_embedding_idx'), table_name='digest_cache', postgresql_ops={'topic_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column('digest_cache', sa.Column('digest_id', sa.UUID(), autoincrement=False, nullable=False))
    op.execute("TRUNCATE digest_cache")
    op.alter_column('digest_cache', 'digest_id', nullable=False)
    op.create_foreign_key(op.f('digest_cache_digest_id_fkey'), 'digest_cache', 'digests', ['digest_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('digest_cache_embedding_idx'), 'digest_cache', ['topic_embedding'], unique=False, postgresql_ops={'topic_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('digest_cache', 'extra_data')
    op.drop_column('digest_cache', 'content')
    # ### end Alembic commands ###
